services:
  bookshopapi:
    image: bookshopapi
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 3001:3001
    environment:
      NODE_ENV: production
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      GOOGLE_CALLBACK_URL: ${GOOGLE_CALLBACK_URL}
      MONGO_URI: ${MONGO_URI}
      JWT_SECRET: ${JWT_SECRET}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      REDIS_PASSWORD: ${REDIS_PASSWORD}

    networks:
        - public
        - private
    depends_on:
      - redis
      - db

  redis:
    image: redis:latest
    ports:
      - 6371:6379
    command: redis-server --requirepass ${REDIS_PASSWORD}  

  db:
    image: mongo:latest
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - db_data:/data/db

    networks:
      - private
    command: mongod --auth 
    restart: always 
    
networks:
  public:
  private: 
volumes:
  db_data:   # Named volume for MongoDB data
